name: RecBole tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install dgl
        pip install xgboost
        pip install community
        pip install networkx
        pip install python-louvain
        pip install lightgbm
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # Use "python -m pytest" instead of "pytest" to fix imports
    - name: Test Overall
      run: |
        python run_recbole.py --model=BPR --epochs=2
    - name: Test metrics
      run: |
        python -m pytest -v tests/metrics
    - name: Test data
      run: |
        python -m pytest -v tests/data
    - name: Test evaluation_setting
      run: |
        python -m pytest -v tests/evaluation_setting
    - name: Test model
      run: |
        python -m pytest -v tests/model/test_model_auto.py
    - name: Test config
      run: |
        python -m pytest -v tests/config/test_config.py
        export PYTHONPATH=.
        python tests/config/test_command_line.py --use_gpu=False --valid_metric=Recall@10 --split_ratio=[0.7,0.2,0.1] --metrics='["Recall"]' --topk=[10] --epochs=200 --eval_setting='LO_RS' --learning_rate=0.3

